INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (9, 'It’s Time to Stop Spraying Cats with Water!', 'Why, oh why, is spraying cats with water still a thing?  In looking around online and talking with people, I find that – over and over again – people are drawn to using a squirt bottle to either discipline or punish cats for unwanted behavior.  Even shelters and those who should know better are still recommending the use of spray bottles or squirt guns.  With everything we now know about cats, learning, and behavior, we need to update this antiquated mode of trying to teach cats to stop one behavior and do something different!
Well, folks who encourage the use of the spray bottle do have one thing right – using a spray bottle may indeed change your cat’s behavior, although not in the way you want it to.  You know all of those stories where a fairy or genie or leprechaun grants three wishes, but the way those wishes are granted usually means something awful happens to the wisher?  You can get similar results when you use a squirt bottle with your cat.  Your cat might stop scratching the couch…only to start scratching on another piece of furniture when you’re not around.  Or, your cat might stop chewing the plants…until you’re not around.  Or, your cat might stop hopping up on the kitchen counters…until you’re not around.  See what I’m getting at?  Your cat won’t necessarily make the connection between his behavior and the squirt bottle, other than he gets squirted when he does those things AND you’re around.  But when you’re not around, there’s no consequence.  So the behavior continues…when you’re not around.

And frankly, squirt or spray bottles may not even be that effective.  I’ll be honest with you.  Many years ago, before I knew what I know now, I used a squirt bottle on a cat I had who was constantly jumping up on our kitchen counters.  It worked the first few times I squirted her – she got down immediately and ran away.  But the behavior continued, and pretty soon, she simply stared me down while I was squirting her and her tiny little face was just like “BRING IT” (she was a tortie and had tortitude, so this was totally in line with her purrsonality).  The spray bottle was completely useless at that point, and all I was doing was 1) showing her that I was mean, and 2) soaking her.  I didn’t have the intention of being mean, of course – my intention was simply to keep her from getting on the counter!  But she didn’t know that, she was just getting squirted down by a big old meanie.  Ahhh, I’m so sorry, Zoe!!!

I’ve also talked with many people who have had similar experiences, where the squirt bottle didn’t do anything to correct the behavior.  And, I’ve even talked with a couple of people who said their cats thought the squirted bottle was a GAME, so they would do things just to get sprayed! (So much for the myth that cats hate water, eh?)

To correct (or change) a cat’s behavior, either punishment (like using a spray bottle) or reinforcement (to reward good behavior) needs to happen consistently – that’s when cats start to put two and two together, linking their behavior with the consequence.  With positive reinforcement, this is fun for everyone – kitty does something good, and you get to be the hero by providing a reward (e.g., a treat) in hopes of encouraging the kitty to repeat that behavior.  The more often you are able to reinforce a desirable behavior, the more likely the cat will repeat it (think consistency).  However, the same is NOT true of using punishment such as a spray bottle.  You will not always be around to punish your cat for doing something undesirable, thus, the punishment will not be consistent.  And the more consistent you are with punishment, the more frequently your cat is receiving bad juju from you.  So, if you are able to be consistent enough with punishment, it comes with a price – fear and distrust.  If you are constantly doling out punishment in the form of spray bottles or even yelling (and I certainly hope not hitting or making physical contact), your cat is more likely to start fearing you.  The end result is more stress for everyone, and when cats get too stressed, that results in…yup, you guessed it…more behavior issues (which can even include aggression towards you).

So what happens when you use a spray bottle, or other method of punishment that comes from you?

Your cat starts to associate the unpleasant experience with you, and not necessarily his actions with the punishment (as you intended).
Your cat will begin to do the undesired “thing” when you’re not around.
Your cat will begin to fear and distrust you.
Your cat’s stress levels may increase, which can result in more of the behavior you are trying to correct, or result in a new undesirable behavior.', '2021-01-17 22:26:52', '2021-01-31 09:04:00', 'PUBLIC', 1);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (16, 'Why do cats love hiding?', 'When a cat finds a good hiding spot, they feel safe and more comfortable than being out in the open.  It’s no wonder why cats enjoy finding spots in our homes that conceal their location – they can snooze in peace and dream about catching the mouse, instead of being the mouse.  In a small little cat cave (whether it’s a box, bag, under the bed, or tucked in a closet), a cat can quickly become familiarized with the small area, fill it with its own scent, and create a safe spot in which to relax. Cats in homes with several people, young children, other animals, etc. will often seek these safe spaces out to get a few moments of “alone time”, which we all need occasionally!

Further, hiding spots are very important to cats who are new to their environment, or who are just beginning to be socialized with people or animals. Cats need a safe spot in these cases – being out in the open and vulnerable to interactions with anyone who comes along can be very stressful and scary to a new cat, and can really be detrimental to the new cat getting to know a new home or learning about humans. I’ve talked with several people who have adopted under-socialized kitties who report that their cat just hides under the bed all of the time.  Obviously, these cats need places to go, but hiding under the bed all the time is not going to help!

I believe that we can do better for these cats by providing them with safe hiding places that can help them adjust to a new home or people. A cat who has stationed herself under the bed is completely unreachable (and attempts to get a scared cat out from under the bed can go very wrong for everyone involved), so blocking off access to the bed or behind a couch and providing alternative hiding spots is preferable. Several alternative hiding spots should be offered, and they can be placed in different orientations; for example, you might put a cat cave in the corner of a room on the top of a cat tree, or put a cardboard box on its side with a towel partially covering the opening opposite a door so the kitty can see who comes and goes. This allows the cat to take on an observational role until she becomes comfortable enough to explore and interact with the things and people in the new environment.

Hiding spots around the home can also help keep the peace in multi-cat families. Cats who are prone to being chased or bullied by more dominant cats (or dogs) in the home will appreciate safe places to hide where they go unnoticed by other animals. While I encourage you to work on improving those relationships where there is aggression happening between animals in your home, providing some safe hiding spots can go a long way to giving your kitties the space they need to peacefully coexist.', '2021-01-18 11:57:27', '2021-01-18 11:57:29', 'PUBLIC', 1);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (29, 'Just a Thought: How Your Cat’s Behavior Issue Affects YOU', 'I just read an interesting article by Kristin Buller called “3 Ways Owners are Impacted by Pets with Behavior Problems“.  Kristin is a licensed clinical social worker and provides veterinary social services to people who care for pets with behavior problems.  In a research project she’s conducting, preliminary results indicate that there are three areas of impact for people who are dealing with their pet’s behavior problems:

Emotional Impact – while you love your pet to pieces, their behavior can cause frustration, anger, and feelings of hopelessness.  The term “emotional roller-coaster” fits well to describe this!
Day-to-Day Life – managing your pet’s behavior problem can cause big changes to your daily life.  Whether it’s medicating your pet, or running around every day after you get home from work to make sure your cat hasn’t peed on anything/scratched anything/ingested anything dangerous that you’ve tried to secure prior to leaving home, management of behavior issues can create a tremendous burden on pets’ caretakers.
Relationships – how you manage your pet’s behavior issue may cause friction between family members who disagree with your course of action, or it may be a source of judgement by friends and family.  Pets are a part of the family, and people have different ways of addressing family problems.  Human relationships are complex, and the relationships we have with our pets can be as well.
In addition to the three above ways the effect of your cat’s behavior issue can create stressors on you and your family, I’d like to add a fourth – and not insignificant – impact:

4.  Financial – how much is your pet’s behavior issue costing you?

For people living with cat behavior problems, this is a factor that shouldn’t be overlooked.  A cat who doesn’t use her litterbox may be costing you hundreds – or even thousands – of dollars in cleaning supplies and services, new clothing or the cost of dry-cleaning, new furniture, new carpet and installation services…not to mention the hours of your time you spend trying to manage the problem and even just worrying about it.  A cat who scratches inappropriate objects in your home causes physical damage to furniture, carpet, and I’ve even seen wooden doorways and banisters destroyed!  Cats who fight with each other can result in expensive vet bills to take care of injuries.  Cats with behavior problems can be pretty dang expensive!', '2021-01-17 00:00:00', '2021-01-21 09:56:00', 'PUBLIC', 5);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (45, 'Cats and Laser Pointers: The Good Stuff', 'As with many things cat-related, the issue of cats and laser pointers is not always black and white.  Many cats LOVE to chase The Red Dot because it’s quick, moves randomly, and resembles one of felines’ favorite prey items: flying and crawling insects.  Laser pointers can get your cat running, jumping, and leaping into the air and provides them with a great form of exercise…plus, it’s FUN for them and the humans who take joy in watching them.  Especially for indoor cats who may not get enough exercise, laser pointers can provide cats with much-needed work-outs.

Additionally, hunting The Red Dot can be a form of mental enrichment that cats miss out on if they aren’t given the opportunity to “hunt” on a regular basis.  Where did the dot go?  Oh, it’s under the chair!  No, wait, it just went behind the sofa…maybe I’ll stalk it here…and, you get the idea.  Hunting The Red Dot is all about mental strategy, and that keeps your kitty’s mind active and healthy, too.  So, there are many positive reasons for incorporating the laser pointer into your cat’s play routine, if she enjoys chasing (or even watching) it!', '2021-01-19 12:07:55', '2021-01-23 08:38:00', 'PUBLIC', 1);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (46, 'The Best Way to Play with Your Cat and Laser Pointers', 'I’m all about giving your cat what she enjoys.  And if your cat loves playing with the laser pointer, go for it!  But try these suggestions to make sure that your cat has a fulfilling play session:

Start your play session off with the laser pointer, but then transition to a wand toy after a few minutes.  You’ll let your cat go through the first two steps of the prey sequence with The Red Dot, but then switch over to a physical toy where she can execute the last two steps (or even go back to the first half, if she wants).
You can also incorporate other types of cat toys in the play session.  Start with the laser pointer as described above, but have several cat toys (like little balls, mice, or kicker toys) scattered around the room.  Use the laser pointer to direct the cat to each toy so that she can pounce/grab and perform the kill bite on a physical object.
End each play session with a treat or a meal, as this rounds out the hunt-catch-kill-eat process that cats follow as predatory beasties.', '2021-01-23 10:39:00', '2021-01-23 10:39:00', 'PUBLIC', 1);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (47, 'How to Build Your Cat’s Trust. Part 1', 'No matter what type of cat you have or what her personality is like, mutual trust in each other must be learned so that you can both enjoy a happy, healthy, relationship.  Whether your cat is shy or fearful, bold or aggressive, there are things you should do to foster her confidence and faith in you.  It’s much easier to build your cat’s trust from the get-go then to try to re-build it after you’ve broken it; however, cats are often forgiving creatures and they don’t hold grudges (and they never act out of revenge or spite – cat’s just don’t think that way).  With time, you can improve (or repair) the relationship with your cat to one of comfort, ease, and predictability.  Here are a few things to keep in mind when trying to build your cat’s trust:

Respect your cat’s space.  Your cat will need some time to settle in if she’s new to the home; some take longer than others to do this.  Let your cat find comfortable spots to hang out, and don’t invade those spaces.  This general rule will continue even after she becomes comfortable in her home.  Cats enjoy their independence and will let you know when they would like your attention (or give you clues as to when they don’t want it, if you are a space-invader!).
Observe body language. Your cat will communicate first and foremost with her body language (see cartoon below).  Respect what she is telling you.  Is she crouched away from you or is her body oriented towards you and more welcoming?  Is she flicking her tail as a sign of annoyance, or is it relaxed?  Pay attention to her ear positions, how wide her eyes are, and body position.
Let your cat come to you. Don’t force a friendship – let your cat decide how comfortable she is and when she wants to interact with you (although you can do some things to encourage interactions, see below).  Cats learn a lot just through observation, so even though you may not be directly interacting with her, she’s learning a lot about you if she’s simply watching you from a window perch or the couch.  Let her watch and learn about your movements, smells, and sounds!', '2021-01-23 10:45:00', '2021-01-23 10:45:00', 'DRAFT', 1);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (48, 'How to Build Your Cat’s Trust. Part 2', 'Learn your cat’s limits to being touched. Take a gradual approach to learning where and how your cat likes to be touched.  Never poke or tease when attempting to touch or pet your cat; always use predictable movements.  Be aware of her body language to learn where and how your cat likes to be stroked or petted.  If your cat has petting aggression, try to limit petting sessions both in terms of where you pet her and for how long.
Give your cat choices and respect the choice she ends up making. Whether it’s a place to nap or perch, or an opportunity to play (or not), letting your cat decide what she wants to do will build her confidence and help her learn that you are not going to force her to do anything.  Cats become stressed when they have no control over their environment (that’s one reason why animal shelters can be so difficult for them), and enjoy having choices about when, what, where, how, and who to interact with.  It’s no fun when someone constantly tries to control what you’re doing, so why would your cat enjoy that?
Be predictable. Try to move and speak in ways that won’t surprise or startle your cat.  Don’t lunge suddenly or stomp on the floor, and try to keep a steady, calm voice.  This applies to all times, not just when you’re directly interacting with your cat.  It can be difficult if you have children or other pets (DOGS) in the house, but if you have a shy kitty, this could be important.  Some cats are very easy-going and don’t really care what’s going on around them and can pretty much nap through anything.  But with a more sensitive kitty, this is a good opportunity to teach children about empathy and the needs of others.
Decide how to make each interaction a positive one for your cat. You have control over whether or not the interactions you have with your cat will be positive or negative.  Play-time can be really fun for both of you, for example, but be careful – what you might think is playing might be interpreted as aggressive teasing or taunting by your cat.  Always use toys to play, and let her catch the toy occasionally.  Before interacting with a particularly sensitive cat, really try to think about what you can do to make that interaction positive so that you build your cat’s trust.  Take every opportunity you can to create a positive association with you!
Use positive reinforcement to reward positive interactions. You can use treats, a soothing voice, play, or even petting (if she likes it) to reward any good behavior.  Further, you can use any of these things to encourage your kitty to do something (like coming out of a hiding spot, for example)…but respect her decision to not do something as well (just don’t provide the reward).  Positive reinforcement, given consistently, can be a great way to build your cat’s trust and communicate that she’s done something good.  It’s also a great way to train your cat to do anything, including tricks…your kitty will appreciate the mental stimulation, and it will give you another great way to bond with her.', '2021-01-23 10:46:00', '2021-01-23 10:46:00', 'PUBLIC', 1);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (53, 'Are Laser Pointers Safe for Cats’ Eyes?', 'One last thing.  We all know that it’s not a great idea to shine lasers into anyone’s eyes, (humans, cats, whatever).  But if the laser ranges from between 1 and 5 milliwatts (the range of most pet toy lasers), they’re fairly safe (but still, don’t shine them in the eye!).  Please do look for the “safe for pets” label on any toy with a laser on it and for the power of the laser because countries outside of the US may have different standards for safety (or no standards). It’s always better to be safe than sorry!', '2021-01-23 10:52:00', '2021-01-24 05:58:00', 'DRAFT', 1);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (54, 'Self-warming cat beds: so cozy, kitty may never want to leave! Part 1', 'Ever since Thomas and I moved into our new house, we’ve been slowly and steadily trying out a variety of cat things for Avery that we never had the room to test out (lest we be overrun by cat stuff) in our humble little studio apartment.

It’s been interesting learning which cat “things” Avery takes to right away, which take a while to stick, which eventually drop out of his favour, and which he never really bothers with at all.
A lot of the things I thought he’d really love he hasn’t been a massive fan of. Like a few of the the small cat trees I grabbed that don’t have perches or spots for him to sleep on – he’s way more into anything that’s got a nap space integrated, though I really should’ve guessed that before!

I’ve been packing the house with cat things as well in the hopes that when we finally get Avery a new brother or sister, he has plenty to scratch, sleep, and run/hide away to in case the new cat (likely a new kitten) gets to be just a bit too much for him and he needs a breather.

It’s good to have a number of different “purrfect spots” ideal for cats to hang out in even if you only have one cat (this helps prevent feline boredom), but if you’ve got multiple furballs, I feel the extra choice become a necessity to a degree, since more spots to hang out in lessens the likelihood cats are going to end up squabbling over the one and only cat bed or cat tree.

With more than one choice, even if cats sometimes bicker, there are plenty of places to take refuge and they can hang out together or spread apart if they need a hot minute away from each other.

Anyway, so that takes us to cat beds. My brother (who blogs over at PetsOverload) has been telling me to buy a cat bed for Avery for ages, and while it was never a priority for me,  I did always know Avery would love it if we bought him a cat bed.

I wanted to buy Avery his first cat tree first, because to me cat tree = place to sleep, scratch, play, a nice high vantage point, etc, while a cat bed = sleep & snuggle, and I always figured my furs, blankets, and all that jazz strewn about were good enough for that.

When I spotted the Trixie Minou on a pretty darn good Black Friday Sale, however, I took the opportunity to add it to cart to give these cat bed things a try.

I’ve temporarily lost my snuggle buddy to a cat bed at this point (though he does still sleep with us at night!), but I really can’t blame him for loving the self-warming cat bed we picked up for him so much.

It’s got a super soft, warm removable pillow lining the bottom that makes it look so comfortable, and because of it’s shape it reminds me of an Eskimo bassinet or an igloo of sorts.

It’s extra warm inside, and seeing as how it’s a little chilly indoors compared to the summer right now, he’s been digging it like mad.

Avery’s gained a little weight because of how little he leaves his self-warming bed nowadays, and I’ll take that to mean I should probably buy a few more of them to scatter around the house so he moves around from one to another like he does with the cat trees.

Either way, no these are not equivalent to a blanket – they are way more loved, at least by my cat. I do imagine the self-warming beds that are are deeper, are like cat houses or even tents, are more fuzzy and snuggle types of warm, and not just flat and low like a blanket would be better loved by any cat, but I could be totally wrong, especially since right now I only have one cat bed to base my theories on.

If you’ve tested out self warming cat beds with your kitty, do let me know in the comments what his or her preferences are and if some, in your experience, are warmer or just plain better loved by your cat than others.', '2021-01-24 19:54:30', '2021-01-24 19:54:31', 'DRAFT', 2);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (60, 'Self-warming cat beds: so cozy, kitty may never want to leave! Part 2', '1. PETMATE ASPEN PET ROUND SELF WARMING BED
Petmate’s Aspen Round Pet Bed is the first thing that comes to mind when I think of self-warming cat beds.

There are quite a lot of pet beds that look quite a lot like this one out there – round, made of ever-so-cozy fabrics, and cushioned along the bottom to comfy perfection – and while I imagine some are a little warmer than others, I do think every one will for the most part be way more well-loved than a standard blanket or sweater.

This particular one by Petmate includes a reflective interior layer to bounce the heat your pet is creating back onto itself.

I’d imagine it to be incredibly warm, and the perfect thing for moving around from one room to another, or sticking by the TV-set so your cat has somewhere to snuggle up when you’re watching.
2. K&H PET PRODUCTS THERMO-KITTY HEATED CAT BED
If you thought “produces its own heat” when you thought of self-warming, this K&H heated cat bed will be a lot more up your alley.

You plug it into the wall, and it automatically heats to be around 12 or 15 degrees Fahrenheit above room temperature.

Then when your furry gets a little chilly, he or she curls up into it and it’s advertised that the dual thermostat heats to around 102 degrees F/38.8 degrees C.

Self-heating cat beds seem to be the perfect way to give a little reminder of summer to your cat during more chilly winter months. Just be sure to only use them indoors if (like this one!) they’re intended for indoor use only.
3. BEST FRIENDS BY SHERI ORTHOCOMFORT DEEP DISH CUDDLER
Now this is a cat bed I don’t think any furball could resist.

The vast majority of self-warming cat beds out there don’t have very high surrounding walls, so to speak, but this one absolutely does.

It almost looks like cats melt into it and become one with the bed. Such ridiculous levels of comfort due to how deep it is, I’m sure.

Needless to say, if I was going to grab a second one for Avery, this would be next up on my list.
4. PETMAKER COZY KITTY TENT IGLOO PLUSH CAT BED
If you’re going for as warm as possible without adding an electric heater to the mix, I do feel that self warming cat tent style beds are the way to go.

They’re fully enclosed, and thus I’d imagine keep heat in way better than typical cat beds that aren’t fully covered.

They’re also easy to line with extra bedding on the bottom and the sides, and essentially work as insulated cat houses in a sense that way.

But they can also be placed inside of cat houses, and are way easier to move around the house to test out which spaces your kitty would prefer it in.
5. ETHICAL PETS SLEEP ZONE CUDDLE CAVE PET BED
If you love the idea of a cat cave style self-warming pet bed, there are quite a few really snug versions of these, so you’re sure to find at least one that’s up your alley.

I think my the Trixie Minou I’ve got qualifies as a cat cave,  though it’s a little more like a baby bassinet than most, but all the caves I’ve seen are for the most part super snug and warm and made of soft, machine washable fabrics.

I couldn’t be happier with the one I’ve got, though this one by Ethical Pets looks a little less pretty and yet a little more snug than the Trixie Minou.

Another really cozy looking cat cave bed you may be interested in checking out? Aingycy’s Self Warming Fleece Cat Bed.', '2021-01-18 14:00:00', '2021-01-18 14:54:39', 'DRAFT', 2);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (61, 'Just A Thought: How to Change Your Cat’s Behavior', 'Your cat is doing something – anything, really – that you would like to change.  Whether it’s not using the litterbox, being aggressive with another cat in the home, or simply jumping up on the counters where you prepare food, you wish that this behavior would stop!  The good news is that you can change your cat’s behavior.  But because cats respond to their environment and those within it, they are not going to change their behavior on their own.  The fact is, the only way to change your cat’s behavior is to change YOUR behavior.  This can include making changes to your cat’s physical environment, establishing new habits for yourself (for example, setting up a scheduled play time for each day), or changing the way you interact with your cat.  Your cat does not have the power to change her environment or her needs; only you can change her environment and control if/how/when her needs are met!
Successful Changes are the Result of Two Things
I’ve worked with a lot of clients to change their cats’ behaviors.  I do not change cats; my clients do.  My job is to provide recommendations for changes my clients need to make to see desirable behaviors.  The most successful clients are ones that are 1) open-minded to change, with a “can-do” attitude, and 2) take the initiative to do the work.  Sometimes it’s easy, other times it’s more challenging.  But the only way your cat will change is if you take the first step to change something yourself.', '2021-01-26 06:11:00', '2021-01-27 03:35:00', 'DRAFT', 5);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (62, 'Cat Care Options While You’re Away', 'Whether you’re traveling for the winter holidays or any other time of the year, it’s always smart to plan ahead when it comes to figuring out your cat care options while you’re away.  As someone whose mom is a professional pet sitter (shameless plug for Comforts at Home Pet Sitting in Vancouver and Camas, WA), I can tell you that pet-sitters get booked up very quickly weeks (and sometimes months) before holidays, so your options will become more limited the longer you wait to decide what your kitty will be doing while you’re away from home. There are a number of options to consider depending on several factors: how long will you be gone, what is your budget, and perhaps most importantly, what will be best for your cat? Is your cat friendly, outgoing, and likes the attention of new people; or is she shy and skittish, and most comfortable in familiar surroundings? You’ll want to answer all of these questions when deciding what to do, but here are some choices to guide you when you’re figuring out what to do.

Cat Care Options While You’re Away
Leave your cats to their own devices.  Yes, this is an option – it’s little to no-cost, and if you’re going to be gone for just a day or two and your cats stay indoors and are in good health, there’s nothing wrong with this as long as your cats are safe and secure.  Before my senior cat started taking daily medication, I used to leave my kitties overnight with plenty of food and water and they would be completely fine.  You can even use automatic timed feeders if you have your cats on a feeding schedule so as not to disrupt their daily routine.  However, I don’t recommend this option if you’ll be gone for more than two days or if you have any concerns about the needs of your cats, whether physical, social, or emotional.
Hire a pet-sitter. Pet-sitters are a great option if your cat tends to be on the shy side and prefers to be in familiar surroundings. Further, if you have more than one cat and they are buddies, they can keep each other company at home. Pet-sitters can be used for both short-term and long-term care, and can visit one or more times per day, but make sure that you do your homework. You’ll want to hire a professional pet-sitter, not just the next-door neighbor kid who is looking to make $10. A professional pet-sitter has training, and is insured, and knows what to do in case of emergencies. Meet with a few in your area and decide who you like and trust, and take a look at their reviews, too. Ask for references!  You’ll be trusting this person to come into your home and care for your beloved furry friends, so make sure you hire the right person for the job.
Hire a house-sitter.  A house-sitter is a step up from a pet-sitter in that a house-sitter usually spends the night at your home while you’re away.  That doesn’t mean that a house-sitter will be there all the time, day and night, but if your kitty has separation anxiety issues or requires more social or emotional care, a house-sitter might be the better option for you.  There are many types of house-sitting gigs out there, both long- and short-term, including pet-sitters who offer house-sitting services.  Again, you’ll want to carefully consider who to bring into your home, but this may offer your kitties a level of comfort that a regular pet-sitter may not be able to provide with just a short daily visit.
Use a boarding facility or a pet hotel. If you cat likes people and attention, you’re going to be away for several days (or longer), or if your kitty has medical needs that need to be regularly monitored or maintained (i.e., your cat needs medications or subcutaneous fluids, etc.), you may be best off boarding your kitty. Many veterinarians provide boarding for their clients; however, these cats tend to be housed in small kennels for the duration of their stay. The benefit in this environment is professional medical care.  But if your cat doesn’t need medical attention, what do you do?  There are now many “hotels” that specifically cater to cats, providing time outside of private enclosures (which they typically refer to as condos or cabanas) to interact and play with staff and other cats (if they get along well with others). In Vancouver, WA, The Cat’s Meow is a luxury boarding facility that has indoor live finches for the cats to watch, and in Portland, OR, Pounce Play & Stay is a deluxe cat hotel that has tons of room in which cats can explore and play. If you’re going to be out of town for a while and your cat craves attention, this may be the best option for you. So investigate – there may be a great boarding facility in your area!
Take your cat with you! Many cats don’t mind traveling, especially if they were acclimated to riding in a carrier or traveling in a car at an early age. There are a ton of articles out there about how to travel with your kitty so I won’t go over the details with you here, but you’ll want to make sure you have all the supplies your cat needs (including medications), current identification, and cat-friendly overnight destinations. Many of us can’t stand being away from our kitties, so if your floof is a good traveling companion and you can plan for it, take her with you!', '2021-01-29 02:08:00', '2021-01-29 02:08:00', 'DRAFT', 11);
INSERT INTO blog.article (id, title, article_text, created_at, updated_at, article_status, user_id) VALUES (64, 'Enrichment for Your Indoor Cat', 'Outdoor Enrichment for Your Indoor Cat
Many of our cats spend their entire lives indoors.  And with good reason, as there are many dangerous aspects to letting cats roam: getting hit by cars; disease; fleas; injuries from wildlife, other cats, and even people; getting lost or stolen; and the danger cats inflict upon native wildlife, to name a few.  However, there is a trade-off.  Indoor cats, even though they’re safer and generally live longer lives than outdoor cats, don’t get to be, well, cats.  We love cats for what they are, and that’s a result of thousands of years of evolution and development of behaviors that have allowed cats to adapt to their environment and niche as both predators and prey.  Cats in the wild (both big and small) hunt, which includes staring, stalking and chasing, pouncing and grabbing, and killing (i.e., the prey sequence); they hide; they climb; they play; and yes, they sleep. They also have social lives that include living with other cats (e.g., lions, or kittens with their mothers, or feral cat colonies), mating, and keeping their territories intact and protected.  These social activities are rich with sensory triggers such as smells, sounds, and even tastes (through the flehmen response, which is kind of a taste/scent combination).  What it comes down to is this: indoor cats have the potential to miss out on a lot of things that cats evolved to experience.  And when indoor cats aren’t given the opportunity to act like cats, they get bored, stressed, and behavior issues can start to crop up.  One of the best things you can do for the well-being and happiness of your cat involves regular enrichment, which is defined as “any artificial or natural item that stimulates a pet physically, mentally, or socially.”  And one of the best ways to do this is to provide outdoor enrichment for your indoor cat.

I think that the culture of having cats is really changing in the United States, and it is shifting towards bringing more and more cats exclusively indoors for the reasons I mentioned above.  It wasn’t until fairly recently in American history that cats were viewed as anything other than “working” animals – they were “allowed” to live in barns and on various properties to keep rodents and other pests under control, and in return, they were given some shelter, and the occasional scrap of food.  In more recent decades though, cats have snuggled their way into our hearts, and we started to think about them more as pets than “employees”.  When I was a kid we had indoor/outdoor cats that would come and go as they pleased.  Theresa and Brownnoser would spend most of their days outside hunting, climbing up in the trees, sleeping in the sun, and playing with insects and the like.  We never had behavior issues with them, and we didn’t even have a litterbox in the house!  But even now, it seems that the indoor/outdoor cat is in decline; as urban and suburban areas become more densely populated, people are more frequently opting to keep their cats indoors all the time.

It has been my observation that behavior problems with “domestic” cats are also on the rise, and it’s my suspicion that this corresponds to the amount of time that we keep our cats inside.  Don’t get me wrong – I’m completely for keeping cats safely indoors, but this requires that we make a commitment to them.  Instead of just pets, many of us now think of our cats as family members.  Either way, that commitment needs to include an environment that stimulates and engages cats in a way that keeps them happy and healthy.  If you get a cat and expect it to simply sleep all day and cuddle all night without any effort on your part, I hate to say it, but you might want to get a stuffed animal instead of a cat.  Otherwise, you’re setting yourself up for disappointment, and placing unrealistic expectations on your kitty.

Giving your cat enrichment doesn’t have to be difficult, time-consuming, or expensive; all it takes is a little creativity.  Think about cats in the wild: what do they do? What do they smell?  What do they see?  What do they hear, taste, and touch?  Is there any way you can replicate those experiences with your cat, in a safe way?  Here are some ideas to get you started:

Bring the Outdoors Inside
Use the five senses (sight, smell, touch, taste, and hearing) to guide you in bringing novel experiences to your cat.  One thing to keep in mind is safety: not everything outside is going to be safe for your cat, so if you are bringing plant material indoors, make sure it is safe for your cat to smell and potentially eat.  It’s a good idea to keep an eye on your cat any time she is interacting with something new just to make sure that something unexpected doesn’t happen and causes injury.  Additionally, you’ll want to rotate or switch out any enrichment items so that they don’t get old and boring; novelty is the spice of life for cats, so make sure they stay on their toes with something new every day.

Sight:  Place bird and/or squirrel feeders outside of windows where your cat can see them.  You can also plant flowers near windows that will attract butterflies and birds.  Place perches and beds near windows so that your cat can enjoy the sights from comfort.  If this isn’t possible where you live, you can try experimenting with animal DVDs that are made just for cats.
Sounds:  If you live in a setting where you can hear birds and wind rushing through trees, you can keep windows and doors open if they are properly screened.  If the sounds of your neighborhood may be more disruptive (i.e., maybe you live in a downtown area with lots of traffic, etc.), you can try music and sound-effect CDs that are made for cats.  Yes, they exist!  A quick google search will yield several options.
Scent:  Try bringing items from the outdoors inside.  These can include leaves, flowers, pine cones, sticks, and even logs that your cat can use as scratchers.  You can suspend smaller items from strings for your cat to sniff and bat at (like a mobile), or hide them in boxes or under blankets for your cat to find.  Make sure that anything you bring inside hasn’t had pesticides or fertilizer applied to it, and that it’s safe for your cat to potentially eat.
Taste:  This is closely related to scent, but you can grow things either indoors or out that your cat will enjoy.  Fresh catnip and cat grass are always a hit with kitties, but you can also grow other cat-friendly herbs and flowers nearly any time of year.  Another thing to consider is hiding your cat’s food or treats throughout her living space; in the wild, cats have to work for their food, and they can hunt up to 20 times per day.  They stick their paws into tiny spaces to extract prey, and explore their area to find food.  Food puzzles are a fun way to make your cat work for her food, or provide a surprise treat if she happens upon it during her daily territory patrol.
Touch:  Again this can be related to the scent category if you are bringing in things from the outdoors for your kitty to play with.  But this may also include things for your cat to climb on or hide in.  Please do get a cat tree (or two) to place near windows, or use shelves so that your cat can explore the room from a different perspective.  Even simply moving a cat tree that has been in the same location for a while can create novelty with an old item!  You can also provide boxes, set up blanket tents, and covered cat beds for your cats to lounge in.  Move these things around occasionally, even to high perching areas.  And don’t forget to place fun objects (treats, cat grass, toys, outdoor objects) on shelves or perches that your cat will come across occasionally!  Finally, try to use realistic toys, especially when using an interactive wand to play with your cat and take her through the prey sequence.  Use toys that resemble prey items like mice, birds, insects, and snakes, and move the toys as those prey would behave.  This will provide a more fulfilling, active play session and keep your cat’s predatory skills honed.
Leash and Harness Training
Your cat doesn’t have to stay indoors all the time.  Some cats enjoy exploring the outdoors while wearing a harness that is attached to a leash.  Training your cat from a young age to enjoy the rewards of wearing a harness is the easiest way to go about this, but mature cats can be taught to wear harnesses too.  Just take everything slowly, step by step, and reward your cat for each step in the process!  The Adventure Cats website has an excellent article about training your cat how to use a harness and leash.  Keep in mind that if you choose to do this, you’ll want to make sure that your cat has current identification and vaccinations, and is treated for fleas.

Catios and Outdoor Enclosures
Finally, if you have the space, you can provide your cat with an enclosed outdoor space, or a catio, to enjoy all the sights, smells, and sounds of nature from a safe place.  Cat fences can prevent cats from leaving your yard, or you can have an enclosed catio of nearly any size.  In fact, you can even build a catio window-box if your yard space is really constrained!  Catios and enclosures come in all sorts of shapes and sizes, and can be built on nearly any type of budget.  There are plenty of resources online, and you can start by reading my article “Outdoor Catios for Enrichment and Entertainment“.  Your cat definitely wants one, and you can probably accommodate her wish one way or another!', '2021-01-31 07:07:00', '2021-01-31 08:29:00', 'PUBLIC', 12);